- name: Install acpid
  apt:
    name: acpid
    state: present
    update_cache: yes

- name: Enable acpid service
  service:
    name: acpid
    state: started
    enabled: yes

- name: Create ACPI event for power button
  copy:
    dest: /etc/acpi/events/powerbtn-kde
    content: |
      event=button/power
      action=/usr/local/bin/toggle-graphical.sh
