# Physical NIC for LAN + SRV VLAN
lan_iface: enp16s0

# Network profile toggles
enable_vlans: false

# Unified bridge network configuration
docker_networks:
  lan:
    name: lan-net
    parent: br-lan
    vlan_id: null
    subnet: "{{ ansible_facts['default_ipv4'].network ~ '/' ~ ansible_facts['default_ipv4'].prefix }}"
    gateway: "{{ ansible_facts['default_ipv4'].gateway }}"
    driver: ipvlan
    # ip_range_prefix: 27  # Must be set per host to avoid IP clashes across docker hosts
  srv:
    name: srv-net
    parent: br-srv
    vlan_id: 10
    subnet: 10.0.0.0/24
    gateway: 10.0.0.1
    driver: ipvlan
    ip_range_prefix: 32 # Disable Docker IPAM assigning IPs from the pool, we will assign static IPs to containers
  iot:
    name: iot-net
    parent: br-iot
    vlan_id: 20
    subnet: 10.0.1.0/24
    gateway: 10.0.1.1
    driver: ipvlan
    # ip_range_prefix: 27  # Must be set per host to avoid IP clashes across docker hosts

# NetworkManager is having issues detecting connectivity on unmanaged interfaces (br-lan)
# This leads to apps relying on NetworkManager thinking there is no network connection
# Thus, we disable NetworkManager entirely and manage all interfaces via networkd
enable_networkmanager: false

# Docker daemon network related settings
docker_address_pool_base: "172.20.0.0/16"
docker_address_pool_size: 24