---
- hosts: all
  roles:
    - role: general
      tags: [ge]
    - role: lvm
      tags: [lvm]
    - role: iam
      tags: [iam]
    - role: desktop-environment
      tags: [de]
    - role: zfs-import
      tags: [zfs]
    - docker
    - role: drivers
      tags: [drivers]
    - role: network-trunked
      tags: [net]
    - role: stacks
      tags: [stacks]
