---
- hosts: all
  become: yes
  become_method: su
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  roles:
    - role: general
      tags: [ge]
    - role: lvm
      tags: [lvm]
    - role: iam
      tags: [iam]
    - role: desktop-environment
      tags: [de]
    - role: zfs-import
      tags: [zfs]
    - docker
    - role: drivers
      tags: [drivers]
    - role: network
      tags: [net]
    - role: stacks
      tags: [stacks]
