- name: Add NVIDIA GPG key
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present

- name: Add NVIDIA Docker repository
  apt_repository:
    repo: deb https://nvidia.github.io/libnvidia-container/stable/debian10/$(ARCH) /
    state: present

- name: Install NVIDIA Container Toolkit
  apt:
    name: nvidia-container-toolkit
    state: present
    update_cache: yes

- name: Restart Docker to apply NVIDIA runtime
  service:
    name: docker
    state: restarted
