- name: Add VSCode APT repository
  ansible.builtin.deb822_repository:
    name: vscode
    types: [deb]
    uris: "https://packages.microsoft.com/repos/code"
    signed_by: "https://packages.microsoft.com/keys/microsoft.asc"
    suites: [stable]
    components: [main]
    state: present
    enabled: yes
  when: "'code' in desktop_apps_apt"

- name: Install APT apps
  ansible.builtin.apt:
    name: "{{ desktop_apps_apt }}"
    update_cache: true
    state: present
  when: desktop_apps_apt | length > 0

- name: Install flatpak
  ansible.builtin.apt:
    name: flatpak
    state: present
  when: desktop_apps_flatpak | length > 0

- name: Ensure Flathub remote is added
  ansible.builtin.command: >
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  args:
    creates: /var/lib/flatpak/repo/flathub.trustedkeys.gpg
  when: desktop_apps_flatpak | length > 0

- name: Install flatpak apps
  ansible.builtin.flatpak:
    name: "{{ desktop_apps_flatpak }}"
    state: present
  when: desktop_apps_flatpak | length > 0
