- name: Add VSCode APT repository
  ansible.builtin.deb822_repository:
    name: vscode
    types: [deb]
    uris: "https://packages.microsoft.com/repos/code"
    signed_by: "https://packages.microsoft.com/keys/microsoft.asc"
    suites: [stable]
    components: [main]
    state: present
    enabled: yes

- name: Add Spotify APT repository
  ansible.builtin.deb822_repository:
    name: spotify
    types: [deb]
    uris: http://repository.spotify.com
    signed_by: https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg
    suites: [stable]
    components: [non-free]
    enabled: true

- name: Install general requirements
  ansible.builtin.apt:
    name:
      - git
      - code
      - spotify-client
    update_cache: true
    state: present

