---
- import_tasks: ifupdown.yml
- import_tasks: networkd.yml
- import_tasks: nm.yml
- import_tasks: verify.yml

# --- Docker networks ---
- name: "Ensure Docker SRV network exists and matches expected config"
  import_tasks: docker.yml
  vars:
    network: "{{ srv_network_name }}"
    parent: br-srv
    subnet: "{{ srv_subnet }}"
    gateway: "{{ srv_gateway }}"

- name: "Ensure Docker LAN network exists and matches expected config"
  import_tasks: docker.yml    
  vars:
    network: "{{ lan_network_name }}"
    parent: br-lan
    subnet: "{{ ansible_facts['default_ipv4'].network ~ '/' ~ ansible_facts['default_ipv4'].prefix }}"
    gateway: "{{ ansible_facts['default_ipv4'].gateway }}"