---
- import_tasks: docker-daemon.yml
- import_tasks: ifupdown.yml
- import_tasks: networkd.yml
- import_tasks: nm.yml
- import_tasks: verify.yml

# --- Docker networks ---

- name: "Ensure Docker bridge networks exist and match expected config"
  include_tasks: docker-network.yml
  loop: "{{ docker_networks | dict2items }}"
  vars:
    network: "{{ item.value.name }}"
    parent: "{{ item.value.parent }}"
    subnet: "{{ item.value.subnet }}"
    gateway: "{{ item.value.gateway }}"
    driver: "{{ item.value.driver }}"
    ip_range_prefix: "{{ item.value.ip_range_prefix }}"
    ip_range: "{{ item.value.subnet.split('/')[0] }}/{{ item.value.ip_range_prefix }}"
  when: enable_vlans
