# --- Configure or disable network manager ---

- name: Configure NetworkManager unmanaged devices
  vars:
    unmanaged_devices:
      - "{{ lan_iface }}"
      - "br-lan"
      - "br-srv"
      - "br-iot"
      - "br-main"
      - "docker0"
      - "docker*"
  ansible.builtin.copy:
    dest: /etc/NetworkManager/conf.d/99-unmanaged-devices.conf
    content: |
      # Managed by Ansible – hybrid_network role
      [keyfile]
      unmanaged-devices={{ ['interface-name:'] | product(unmanaged_devices) | map('join') | join(';') }}
  notify:
    - restart NetworkManager
  when: enable_networkmanager

- name: Disable and mask NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: stopped
    enabled: false
    masked: true
  when: not enable_networkmanager