---
- name: Upgrade APT packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes

- name: Check if flatpak is installed
  ansible.builtin.stat:
    path: /usr/bin/flatpak
  register: _flatpak_bin

- name: Update flatpak apps
  ansible.builtin.command: flatpak update --noninteractive
  when: _flatpak_bin.stat.exists
  changed_when: false
