- name: Install UFW firewall
  apt:
    name: ufw
    state: present

- name: Open ports
  ufw:
    rule: allow
    port: "{{ item }}"
  loop: "{{ open_ports }}"

- name: Enable UFW
  ufw:
    state: enabled

- name: Ensure system is updated
  apt:
    upgrade: dist
    update_cache: yes

#- name: Harden SSH config
#  lineinfile:
#    path: /etc/ssh/sshd_config
#    regexp: '^#?PermitRootLogin'
#    line: 'PermitRootLogin no'
#    state: present
#  notify: Restart SSH

#- name: Restart SSH
#  service:
#    name: ssh
#    state: restarted

- name: Install sudo
  apt:
    name: sudo
    state: present

- name: Ensure sudoers users are present
  user:
    name: "{{ item }}"
    state: present
  loop: "{{ sudoers }}"

- name: Add sudoers users to sudoers file
  copy:
    dest: "/etc/sudoers.d/{{ item }}"
    content: "{{ item }} ALL=(ALL) ALL"
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'
  loop: "{{ sudoers }}"
