- name: Apply LVM configuration
  ansible.builtin.include_tasks: apply.yml
  when: lvm_lvs is defined

- name: Discover and save LVM configuration
  ansible.builtin.include_tasks: discover.yml
  when: lvm_lvs is not defined
